Added CLOSE message handling
eclipse-zenoh/zenoh-pico pull request #208
Opened 2023-04-25 14:06 UTC by hairymnstr

There was nothing making the read task finish if it received a CLOSE message.  This meant that if zenohd was restarted a UDP publisher may continue bombarding it with publications indefinitely while it replied with CLOSE which was ignored.

2023-06-15 14:31 UTC, Mallets requested changes

2023-06-15 14:31 UTC, Mallets commented on src/transport/multicast/link/task/read.c
> +                bool should_close = (_Z_MID(t_msg._header) == _Z_MID_CLOSE);
The read task in multicast should never be stopped in response of a close message.
The same read task is used to read all multicast messages from all the peers, so one peer could stop the communication with all the other peers.

Hence, proposed changes to multicast should be reverted.

2023-06-15 14:31 UTC, Mallets commented on src/transport/unicast/link/task/read.c
> +            bool should_close = (_Z_MID(t_msg._header) == _Z_MID_CLOSE);
The message inspection should be done by `_z_unicast_handle_transport_message` which in turn should return an appropriate error code. If `ret != _Z_RES_OK` then the task is already marked as non running at line `95` below.

2023-06-16 07:41 UTC, cguimaraes commented
I think the solution shall be target in a different place of the codebase. Namely, on the handler of the CLOSE message, by triggering the `_z_close` operation.
This is signaling the tasks to terminate on their next loop, thus not requiring to be complexified with extra control variables and checks.

2023-06-16 07:41 UTC, cguimaraes requested changes
I think the solution shall be target in a different place of the codebase. Namely, on the handler of the CLOSE message, by triggering the _z_close operation.
This is signaling the tasks to terminate on their next loop, thus not requiring to be complexified with extra control variables and checks.

2023-12-18 14:21 UTC, closed without merging