NULL task pointers when creation fails.
eclipse-zenoh/zenoh-pico pull request #213
Opened 2023-05-02 10:51 UTC by hairymnstr

If task creation (start read/lease tasks) failed the _z_task_t was freed but the pointer was left in session.  This caused invalid memory access on FreeRTOS based ports (e.g. ESP IDF) when the session was subsequently closed.

2023-05-02 12:56 UTC, cguimaraes commented on src/net/session.c
> +                zn->_tp._transport._unicast._read_task = NULL;
can you also change the previous line `z_free(task)` --> `z_free(zn->_tp._transport._unicast._read_task)`.

2023-05-02 12:58 UTC, cguimaraes requested changes
Since we have the process for the new release already ongoing, we will postpone this merge to just after the release.

2023-05-02 12:58 UTC, cguimaraes commented on src/net/session.c
>              }
can you also change the previous line `z_free(task)` --> `z_free(zn->_tp._transport._unicast._read_task)`.

2023-05-02 12:58 UTC, cguimaraes commented on src/net/session.c
> +                zn->_tp._transport._unicast._read_task = NULL;
can you also change the previous line `z_free(task)` --> `z_free(zn->_tp._transport._unicast._read_task)`.

2023-05-02 12:58 UTC, cguimaraes commented on src/net/session.c
> +                zn->_tp._transport._unicast._lease_task = NULL;
can you also change the previous line `z_free(task)` --> `z_free(zn->_tp._transport._unicast._read_task)`.

2023-05-02 12:58 UTC, cguimaraes commented on src/net/session.c
> +                zn->_tp._transport._multicast._lease_task = NULL;
can you also change the previous line `z_free(task)` --> `z_free(zn->_tp._transport._unicast._read_task)`.

2023-05-10 06:39 UTC, cguimaraes commented
@hairymnstr can you apply the proposed changes?

2023-12-18 14:20 UTC, Mallets commented
Reverted to issue #300

2023-12-18 14:20 UTC, closed without merging