Zenoh-C z_slice and z_bytes types compatibility
eclipse-zenoh/zenoh-pico pull request #417
Opened 2024-06-10 13:11 UTC by jean-roland

This PR will solve #414.

To-do list:
- [ ] Rename current bytes types as slice types
- [ ] Replace direct slice access with methods `z_slice_len` and `z_slice_data`
- [ ] Introduce bytes type with private internals
- [ ] Introduce methods to encode/decode bytes to and from regular types

2024-06-12 09:20 UTC, jean-roland commented
Could you review it @sashacmc

2024-06-12 11:14 UTC, sashacmc requested changes

2024-06-12 11:15 UTC, sashacmc commented on include/zenoh-pico/net/encoding.h
> +    _z_slice_t schema;
I created issue for it
https://github.com/eclipse-zenoh/zenoh-pico/issues/418

2024-06-12 12:40 UTC, jean-roland commented on examples/arduino/z_sub.ino
> +    std::string val((const char *)z_bytes_data(payload), z_bytes_len(payload));
I see

2024-06-12 18:58 UTC, sashacmc approved these changes

2024-06-12 18:58 UTC, sashacmc commented on include/zenoh-pico/collections/slice.h
> + *   uint8_t *val: A pointer to the bytes array.
```suggestion
 *   uint8_t *start: A pointer to the bytes array.
```

2024-06-13 08:29 UTC, milyin commented on src/collections/slice.c
> +    memcpy(&val, bs->_slice.start, sizeof(val));
To be fixed separately, issue #420

2024-06-13 08:53 UTC, milyin approved these changes

2024-06-13 08:54 UTC, merged