Switch reliability from publisher to subscriber.
eclipse-zenoh/zenoh-pico pull request #630
Opened 2024-09-06 08:43 UTC by jean-roland

Closes #614.

* Reliability is now a property of publisher and put/delete instead of subscriber
* You can retrieve in a sample the reliability it was received with.

2024-09-06 10:09 UTC, sashacmc approved these changes
LGTM!

2024-09-06 15:08 UTC, milyin requested changes

2024-09-06 15:08 UTC, milyin commented on include/zenoh-pico/api/types.h
> +    z_reliability_t reliability;
reliability is not under `Z_FEATURE_UNSTABLE_API` anymore ?

2024-09-09 11:33 UTC, milyin approved these changes

2024-09-09 11:33 UTC, merged