Add z_bytes example
eclipse-zenoh/zenoh-pico pull request #673
Opened 2024-09-16 16:04 UTC by jean-roland

Closes #662.

Adds missing encoding constants.

2024-09-17 15:41 UTC, sashacmc requested changes

2024-09-17 15:41 UTC, sashacmc commented on src/api/api.c
> +const z_owned_encoding_t ENCODING_ZENOH_BYTES = {
It would be nice to define some macro to avoid repeating the definition code so many times.
And also use a separate file to avoid overloading api.c

2024-09-18 10:44 UTC, DenisBiryukov91 commented on include/zenoh-pico/api/encoding.h
> +extern const z_owned_encoding_t ENCODING_ZENOH_BYTES;
please see how encoding constants are implemented in zenoh-c: https://github.com/eclipse-zenoh/zenoh-c/blob/610a4b9057a703ecba5f098e084bdc40e4e786f3/include/zenoh_commons.h#L2254

2024-09-19 09:51 UTC, DenisBiryukov91 commented
We will also need to add the docs, and probably an example of using slice iterator similar to https://github.com/eclipse-zenoh/zenoh/blob/db755e3e75733b10cd9b9fa63acb624fd4e57a39/examples/examples/z_bytes.rs#L107C1-L112C6

2024-09-19 13:00 UTC, DenisBiryukov91 commented on examples/unix/c11/z_bytes.c
> +               (int)z_slice_len(z_view_slice_loan(&curr_slice)),
this is not good since it will print garbage, could we rather print slice content as list of hexadecimal values ?

2024-09-19 17:15 UTC, sashacmc approved these changes

2024-09-20 07:51 UTC, merged