Add platform_common.c to zephyr CMakeLists.txt file
eclipse-zenoh/zenoh-pico pull request #778
Opened 2024-11-06 13:09 UTC by sashacmc

2024-11-06 14:08 UTC, WilliamGFish requested changes
GLOB_RECURSE includes the subdirectories, hence pulls in all other platform files.

> external/zenoh-pico/src/system/arduino/esp32/system.c:15:10: fatal error: Arduino.h: No such file or directory
>    15 | #include <Arduino.h>

2024-11-06 14:08 UTC, WilliamGFish commented on zephyr/CMakeLists.txt
> +  "../src/system/*.c"
As this is flagged as GLOB_RECURSE it includes all the subdirectories....lots of odd errors from other platforms.

Try adding to the next list like:
```
file (GLOB Sources_Zephyr 
"../src/system/zephyr/*.c"
"../src/system/*.c"
)
```

2024-11-06 15:54 UTC, WilliamGFish approved these changes

2024-11-07 08:45 UTC, Mallets approved these changes

2024-11-07 08:45 UTC, merged